### PR TITLE
Can't compile with go 1.18 because quic-go is too old

### PR DESCRIPTION
**Pull request by sommio**
### 1. What does this change do, exactly?

Sorry for abusing the PR, but I don't think this issue should be reported to caddyserver/forwardproxy. I simply updated quic-go with the latest version

### 2. Please link to the relevant issues.

go version go1.18.1 linux/amd64:

```
2022/04/19 08:30:39 [INFO] Temporary folder: /tmp/buildenv_2022-04-19-0830.4030436177
2022/04/19 08:30:39 [INFO] Writing main module: /tmp/buildenv_2022-04-19-0830.4030436177/main.go
2022/04/19 08:30:39 [INFO] Initializing Go module
2022/04/19 08:30:39 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy 
go: creating new go.mod: module caddy
go: to add module requirements and sums:
	go mod tidy
2022/04/19 08:30:39 [INFO] Replace github.com/caddyserver/forwardproxy => github.com/klzgrad/forwardproxy@naive
2022/04/19 08:30:39 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive 
2022/04/19 08:30:39 [INFO] Pinning versions
2022/04/19 08:30:39 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.4.6 
go: added github.com/beorn7/perks v1.0.1
go: added github.com/caddyserver/caddy/v2 v2.4.6
go: added github.com/caddyserver/certmagic v0.15.2
go: added github.com/cespare/xxhash/v2 v2.1.1
go: added github.com/golang/protobuf v1.5.2
go: added github.com/google/uuid v1.3.0
go: added github.com/klauspost/cpuid/v2 v2.0.9
go: added github.com/libdns/libdns v0.2.1
go: added github.com/matttproud/golang_protobuf_extensions v1.0.1
go: added github.com/mholt/acmez v1.0.1
go: added github.com/miekg/dns v1.1.43
go: added github.com/prometheus/client_golang v1.11.0
go: added github.com/prometheus/client_model v0.2.0
go: added github.com/prometheus/common v0.26.0
go: added github.com/prometheus/procfs v0.6.0
go: added go.uber.org/atomic v1.7.0
go: added go.uber.org/multierr v1.6.0
go: added go.uber.org/zap v1.19.0
go: added golang.org/x/crypto v0.0.0-20210915214749-c084706c2272
go: added golang.org/x/net v0.0.0-20210913180222-943fd674d43e
go: added golang.org/x/sys v0.0.0-20210915083310-ed5796bab164
go: added golang.org/x/term v0.0.0-20210503060354-a79de5458b56
go: added golang.org/x/text v0.3.7
go: added google.golang.org/protobuf v1.27.1
2022/04/19 08:30:42 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddy-dns/cloudflare 
go: added github.com/caddy-dns/cloudflare v0.0.0-20210607183747-91cf700356a1
go: added github.com/libdns/cloudflare v0.1.0
2022/04/19 08:30:44 [INFO] Build environment ready
2022/04/19 08:30:44 [INFO] Building Caddy
2022/04/19 08:30:44 [INFO] exec (timeout=0s): /usr/bin/go mod tidy 
go: found github.com/caddyserver/forwardproxy in github.com/caddyserver/forwardproxy v0.0.0-00010101000000-000000000000
2022/04/19 08:30:45 [INFO] exec (timeout=0s): /usr/bin/go build -o /tmp/makepkg/caddy-naiveproxy/src/caddy -ldflags -w -s -trimpath 
# github.com/lucas-clemente/quic-go/internal/qtls
/home/sommio/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.23.0/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
2022/04/19 08:30:45 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-04-19-0830.4030436177
2022/04/19 08:30:45 [FATAL] exit status 2
```

### 3. Checklist

- [Yes] I have written tests and verified that they fail without my change

### CODE REVIEW

**Comment by sommio** [comment]
> ### 1. What does this change do, exactly?
> Sorry for abusing the PR, but I don't think this issue should be reported to caddyserver/forwardproxy. I simply updated quic-go with the latest version
> 
> ### 2. Please link to the relevant issues.
> go version go1.18.1 linux/amd64:
> 
> ```
> 2022/04/19 08:30:39 [INFO] Temporary folder: /tmp/buildenv_2022-04-19-0830.4030436177
> 2022/04/19 08:30:39 [INFO] Writing main module: /tmp/buildenv_2022-04-19-0830.4030436177/main.go
> 2022/04/19 08:30:39 [INFO] Initializing Go module
> 2022/04/19 08:30:39 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy 
> go: creating new go.mod: module caddy
> go: to add module requirements and sums:
> 	go mod tidy
> 2022/04/19 08:30:39 [INFO] Replace github.com/caddyserver/forwardproxy => github.com/klzgrad/forwardproxy@naive
> 2022/04/19 08:30:39 [INFO] exec (timeout=10s): /usr/bin/go mod edit -replace github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive 
> 2022/04/19 08:30:39 [INFO] Pinning versions
> 2022/04/19 08:30:39 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.4.6 
> go: added github.com/beorn7/perks v1.0.1
> go: added github.com/caddyserver/caddy/v2 v2.4.6
> go: added github.com/caddyserver/certmagic v0.15.2
> go: added github.com/cespare/xxhash/v2 v2.1.1
> go: added github.com/golang/protobuf v1.5.2
> go: added github.com/google/uuid v1.3.0
> go: added github.com/klauspost/cpuid/v2 v2.0.9
> go: added github.com/libdns/libdns v0.2.1
> go: added github.com/matttproud/golang_protobuf_extensions v1.0.1
> go: added github.com/mholt/acmez v1.0.1
> go: added github.com/miekg/dns v1.1.43
> go: added github.com/prometheus/client_golang v1.11.0
> go: added github.com/prometheus/client_model v0.2.0
> go: added github.com/prometheus/common v0.26.0
> go: added github.com/prometheus/procfs v0.6.0
> go: added go.uber.org/atomic v1.7.0
> go: added go.uber.org/multierr v1.6.0
> go: added go.uber.org/zap v1.19.0
> go: added golang.org/x/crypto v0.0.0-20210915214749-c084706c2272
> go: added golang.org/x/net v0.0.0-20210913180222-943fd674d43e
> go: added golang.org/x/sys v0.0.0-20210915083310-ed5796bab164
> go: added golang.org/x/term v0.0.0-20210503060354-a79de5458b56
> go: added golang.org/x/text v0.3.7
> go: added google.golang.org/protobuf v1.27.1
> 2022/04/19 08:30:42 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddy-dns/cloudflare 
> go: added github.com/caddy-dns/cloudflare v0.0.0-20210607183747-91cf700356a1
> go: added github.com/libdns/cloudflare v0.1.0
> 2022/04/19 08:30:44 [INFO] Build environment ready
> 2022/04/19 08:30:44 [INFO] Building Caddy
> 2022/04/19 08:30:44 [INFO] exec (timeout=0s): /usr/bin/go mod tidy 
> go: found github.com/caddyserver/forwardproxy in github.com/caddyserver/forwardproxy v0.0.0-00010101000000-000000000000
> 2022/04/19 08:30:45 [INFO] exec (timeout=0s): /usr/bin/go build -o /tmp/makepkg/caddy-naiveproxy/src/caddy -ldflags -w -s -trimpath 
> # github.com/lucas-clemente/quic-go/internal/qtls
> /home/sommio/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.23.0/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
> 2022/04/19 08:30:45 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-04-19-0830.4030436177
> 2022/04/19 08:30:45 [FATAL] exit status 2
> ```
> 
> ### 3. Checklist
> * [Yes] I have written tests and verified that they fail without my change

**Comment by klzgrad** [comment]
```
caddy/v2@v2.5.1/listeners.go:187:68: undefined: quic.EarlySession
```

**Comment by klzgrad** [comment]
The issue no longer happens.
